// 延伸閱讀（單一來源）：key＝App 的 section id 或里程碑 id（M0–M6）
// 每一筆都在 2026-09-17 實際打開核對過標題與內容，論文 DOI 經 Crossref 核對；改連結後請重新檢查

export const READING_NOTE = '連結都在 2026-09-17 實際打開核對過，網站改版可能讓連結失效，發現打不開請告訴老師。'

export const READINGS = {
  "project": [
    {"type": "書", "lang": "en", "title": "After Man: A Zoology of the Future", "by": "Dougal Dixon", "year": "1981", "url": "https://www.dougal-dixon.co.uk/after-man", "note": "推測演化經典，想像人類滅絕後動物如何演化成新物種。"},
    {"type": "書", "lang": "en", "title": "All Tomorrows", "by": "C.M. Kösemen (Nemo Ramjet)", "year": "2006", "url": "https://en.wikipedia.org/wiki/All_Tomorrows", "note": "作者免費公開全書，示範怎麼把演化想像畫成完整世界觀。"},
    {"type": "影片", "lang": "en", "title": "The Future Is Wild", "by": "Dougal Dixon, John Adams", "year": "2002", "url": "https://en.wikipedia.org/wiki/The_Future_Is_Wild", "note": "紀錄片形式呈現五百萬到兩億年後的生物，示範分階段推演設定。"},
    {"type": "科普文章", "lang": "zh", "title": "《物種源始》：世界上最有影響力的一本書", "by": "魏妤亘／科技大觀園", "year": "2019", "url": "https://scitechvista.nat.gov.tw/Article/C000003/detail?ID=00cb2d77-d066-4431-845d-fa457e08e3cc", "note": "用達爾文加拉巴哥雀鳥的故事，說明天擇怎麼讓物種分化。"},
    {"type": "科普文章", "lang": "zh", "title": "猜想生物", "by": "維基百科", "year": "", "url": "https://zh.wikipedia.org/zh-tw/猜想生物", "note": "推測演化學一詞的中文入門說明，可當課程用語對照。"},
  ],
  "creature": [
    {"type": "科普文章", "lang": "zh", "title": "無所不在處處都在–極端環境下的太古生物", "by": "賴美津（演講）／科技大觀園", "year": "", "url": "https://scitechvista.nat.gov.tw/Article/C000003/detail?ID=c967225b-878b-45d7-93f1-fe9b1d60cea9", "note": "介紹極端環境生物與化學合成、共生現象，離開陽光也能活的生物邏輯。"},
    {"type": "科普文章", "lang": "zh", "title": "深海熱泉生態系(Hydrothermal Vent Ecosystems)-下", "by": "張世玪、張永達／臺灣大學科學Online", "year": "2010", "url": "https://case.ntu.edu.tw/highscope/%E6%B7%B1%E6%B5%B7%E7%86%B1%E6%B3%89%E7%94%9F%E6%85%8B%E7%B3%BBhydrothermal-vent-ecosystems-%E4%B8%8B/index.html", "note": "解釋深海熱泉生物靠化學合成細菌共生維生，適合設計無光物種。"},
    {"type": "科普文章", "lang": "zh", "title": "炎炎夏日是否快受不了？快來認識這些超耐熱的動物！", "by": "國家地理雜誌中文網", "year": "", "url": "https://www.natgeomedia.com/environment/article/content-16367.html", "note": "用真實動物案例說明環境如何逼出耐熱身體構造與行為策略。"},
    {"type": "科普文章", "lang": "zh", "title": "台灣特有烏頭翁 怕白頭的來雜交", "by": "環境資訊中心", "year": "", "url": "https://e-info.org.tw/node/42947", "note": "台灣本土真實案例，說明雜交如何威脅物種界線與基因純度。"},
    {"type": "科普文章", "lang": "zh", "title": "從演化觀點看男女有別與男歡女愛", "by": "林良恭／科技大觀園", "year": "", "url": "https://scitechvista.nat.gov.tw/Article/c000003/detail?ID=7ac1d1c2-6811-4f01-a7df-1e1d042d4507", "note": "說明天擇與性擇如何一起決定求偶與繁殖策略，設計生物前先讀。"},
    {"type": "影片", "lang": "en", "title": "How trees talk to each other", "by": "Suzanne Simard", "year": "2016", "url": "https://www.ted.com/talks/suzanne_simard_how_trees_talk_to_each_other", "note": "菌根網路讓森林裡的樹互相傳訊號與養分，共生也是一種溝通。"},
    {"type": "影片", "lang": "en", "title": "How bacteria \"talk\"", "by": "Bonnie Bassler", "year": "2009", "url": "https://www.ted.com/talks/bonnie_bassler_how_bacteria_talk", "note": "細菌靠化學訊號集體決策的群體感應，是最小尺度的生物溝通。"},
  ],
  "method": [
    {"type": "教學", "lang": "en", "title": "SIFT (The Four Moves)", "by": "Mike Caulfield", "year": "2019", "url": "https://hapgood.us/2019/06/19/sift-the-four-moves/", "note": "查證資訊來源的四步驟方法，AI給的內容也要照樣核對。"},
    {"type": "教學", "lang": "en", "title": "Civic Online Reasoning（橫向閱讀教材）", "by": "Digital Inquiry Group（原史丹佛歷史教育小組）", "year": "", "url": "https://cor.inquirygroup.org/", "note": "史丹佛教的橫向閱讀，離開頁面查別處說法再判斷。"},
    {"type": "教學", "lang": "zh", "title": "必修：辨識假訊息的識讀心法", "by": "台灣事實查核中心", "year": "2025", "url": "https://school.tfc-taiwan.org.tw/learning-resources/media-literacy/", "note": "台灣事實查核中心教SIFT與疑想查問戳，好懂又在地。"},
    {"type": "論文", "lang": "en", "title": "Lateral reading: College students learn to critically evaluate internet sources in an online course", "by": "Joel Breakstone, Mark Smith, Priscilla Connors, Teresa Ortega, Darby Kerr, Sam Wineburg", "year": "2021", "url": "https://doi.org/10.37016/mr-2020-56", "note": "美國實驗證實橫向閱讀教了就會用，查證力明顯進步。"},
    {"type": "科普文章", "lang": "zh", "title": "不以星星數來判斷Github專案是否值得推薦", "by": "Ivon", "year": "", "url": "https://ivonblog.com/posts/github-is-not-a-social-media/", "note": "台灣工程師提醒，星星數不能當作專案品質保證。"},
    {"type": "官方文件", "lang": "zh", "title": "開源衡量準則", "by": "GitHub Open Source Guides", "year": "", "url": "https://opensource.guide/zh-hant/metrics/", "note": "官方教材列出評估開源專案的具體指標，別只看星星。"},
  ],
  "M0": [
    {"type": "影片", "lang": "en", "title": "Transformers, the tech behind LLMs | Deep Learning Chapter 5（原名 But what is a GPT?）", "by": "3Blue1Brown (Grant Sanderson)", "year": "2024", "url": "https://www.youtube.com/watch?v=wjZofJX0v4M", "note": "動畫解釋Transformer怎麼運作，有中文字幕可開。"},
    {"type": "科普文章", "lang": "zh", "title": "OpenAI 新研究找到 AI 幻覺來源，或能解決這最大問題", "by": "TechNews 科技新報", "year": "2025", "url": "https://technews.tw/2025/09/08/openais-new-study-finds-the-source-of-ai-hallucinations/", "note": "OpenAI自己說明幻覺怎麼來的，中文報導清楚好讀。"},
    {"type": "官方文件", "lang": "zh", "title": "什麼是 Mac 的「終端機」？", "by": "Apple 支援", "year": "", "url": "https://support.apple.com/zh-tw/guide/terminal/trmld4c92d55/mac", "note": "先搞懂終端機是什麼再開始，蘋果官方繁中說明。"},
    {"type": "官方文件", "lang": "zh", "title": "什麼是 PowerShell？", "by": "Microsoft Learn", "year": "", "url": "https://learn.microsoft.com/zh-tw/powershell/scripting/overview?view=powershell-7.6", "note": "Windows同學對照看，觀念和Mac終端機互通。"},
    {"type": "教學", "lang": "zh", "title": "終端機是什麼？Mac 使用者一定要學的超實用指令", "by": "T客邦", "year": "2025", "url": "https://www.techbang.com/posts/125106-mac-terminal-basics", "note": "中文版基礎指令教學，動手打幾行比看說明有感。"},
  ],
  "M1": [
    {"type": "書", "lang": "zh", "title": "沒有我們的世界", "by": "Alan Weisman（艾倫．魏斯曼）／劉泗翰譯", "year": "2008", "url": "https://www.books.com.tw/products/0010405936", "note": "逐年推演人類消失後城市與生態如何變化，是這門課的世界觀範本。"},
    {"type": "論文", "lang": "en", "title": "Long-term census data reveal abundant wildlife populations at Chernobyl", "by": "T.G. Deryabina et al.", "year": "2015", "url": "https://doi.org/10.1016/j.cub.2015.08.017", "note": "車諾比禁區真實普查資料，是課堂想像世界前該看的第一手證據。"},
    {"type": "官方文件", "lang": "en", "title": "Chernobyl, Ukraine", "by": "NASA Earth Observatory", "year": "", "url": "https://science.nasa.gov/earth/earth-observatory/chernobyl-ukraine-39679", "note": "NASA衛星影像對照人類撤離前後的植被變化，證據具體好懂。"},
    {"type": "科普文章", "lang": "zh", "title": "動物在人跡罕至的車諾比與其他地方蓬勃發展", "by": "國家地理雜誌中文網", "year": "", "url": "https://www.natgeomedia.com/environment/article/content-5884.html", "note": "繁體中文說明車諾比野生動物數量回升的觀察與爭議。"},
    {"type": "官方文件", "lang": "zh", "title": "論壇：眼見不為憑——查證作為媒體素養的第一步", "by": "台灣科技媒體中心（SMC）", "year": "", "url": "https://smctw.tw/8769", "note": "教怎麼查證科學說法真假，做世界研究前先練這個習慣。"},
    {"type": "科普文章", "lang": "en", "title": "Scientists can't agree about Chernobyl's impact on wildlife", "by": "Katarina Zimmer／Knowable Magazine", "year": "2022", "url": "https://knowablemagazine.org/content/article/food-environment/2022/scientists-cant-agree-about-chernobyls-impact-wildlife", "note": "同一個車諾比，不同研究團隊結論相反，示範科學事實要多方查證。"},
  ],
  "M2": [
    {"type": "官方文件", "lang": "en", "title": "p5.js Tutorials", "by": "p5.js Foundation", "year": "", "url": "https://p5js.org/tutorials/", "note": "官方教學總覽，找繪圖與互動基礎的入門單元練習。"},
    {"type": "官方文件", "lang": "en", "title": "p5.js Reference", "by": "p5.js Foundation", "year": "", "url": "https://p5js.org/reference/", "note": "查每個函式怎麼用，寫程式卡住時第一個查的地方。"},
    {"type": "官方文件", "lang": "en", "title": "p5.js Web Editor", "by": "p5.js Foundation", "year": "", "url": "https://editor.p5js.org/", "note": "免安裝直接寫程式碼跑畫面，上課與交作業都用它。"},
    {"type": "教學", "lang": "en", "title": "Code! Programming with p5.js", "by": "Daniel Shiffman / The Coding Train", "year": "", "url": "https://thecodingtrain.com/tracks/code-programming-with-p5-js", "note": "跟著影片從形狀、變數練到迴圈，零基礎入門的完整路線。"},
    {"type": "影片", "lang": "zh", "title": "p5.js 互動藝術程式創作入門（程度：初階）｜吳哲宇（上）", "by": "吳哲宇 Che-Yu Wu / 臺灣當代文化實驗場 C-LAB", "year": "", "url": "https://www.youtube.com/watch?v=USBfICElYQ8", "note": "台灣創作者中文講解，適合完全沒寫過程式的人先看。"},
    {"type": "影片", "lang": "zh", "title": "p5.js 互動藝術程式創作入門（程度：初階）｜吳哲宇（下）", "by": "吳哲宇 Che-Yu Wu / 臺灣當代文化實驗場 C-LAB", "year": "", "url": "https://www.youtube.com/watch?v=o_nPnNjDPxk", "note": "接續上集，練習用程式畫出會動的互動圖形效果。"},
  ],
  "M3": [
    {"type": "書", "lang": "en", "title": "The Nature of Code — Chapter 5: Autonomous Agents", "by": "Daniel Shiffman", "year": "", "url": "https://natureofcode.com/autonomous-agents/", "note": "講清楚轉向力怎麼讓一個點看起來像有意志地移動。"},
    {"type": "書", "lang": "en", "title": "The Nature of Code — Chapter 2: Forces", "by": "Daniel Shiffman", "year": "", "url": "https://natureofcode.com/forces/", "note": "先懂力怎麼加在物體上，是後面行為模擬的基礎觀念。"},
    {"type": "書", "lang": "en", "title": "The Nature of Code — Appendix: Creature Design", "by": "Daniel Shiffman / Zannah Marsh", "year": "", "url": "https://natureofcode.com/appendix-creature/", "note": "教怎麼用簡單形狀畫出生物，外形能暗示牠的個性與行為。"},
    {"type": "科普文章", "lang": "en", "title": "Steering Behaviors For Autonomous Characters", "by": "Craig Reynolds", "year": "", "url": "https://www.red3d.com/cwr/steer/", "note": "轉向行為的原始整理，尋找、追逐、閃避都從這裡來。"},
    {"type": "書", "lang": "en", "title": "Vehicles: Experiments in Synthetic Psychology", "by": "Valentino Braitenberg", "year": "1984", "url": "https://mitpress.mit.edu/9780262521123/vehicles/", "note": "簡單線路接法就長出像有情緒的行為，設計物種很好的靈感。"},
    {"type": "影片", "lang": "en", "title": "5.1 Steering Agents", "by": "Daniel Shiffman / The Coding Train", "year": "", "url": "https://thecodingtrain.com/tracks/the-nature-of-code-2/noc/5-autonomous-agents/1-steering-agents", "note": "影片版自主代理入門，先懂觀念再自己動手寫程式碼。"},
  ],
  "M4": [
    {"type": "書", "lang": "en", "title": "The Nature of Code — Chapter 9: Evolutionary Computing", "by": "Daniel Shiffman", "year": "", "url": "https://natureofcode.com/genetic-algorithms/", "note": "講清楚演化運算的流程，適應、選擇、變異怎麼寫成程式。"},
    {"type": "教學", "lang": "en", "title": "#29 — Smart Rockets in p5.js", "by": "Daniel Shiffman / The Coding Train", "year": "", "url": "https://thecodingtrain.com/challenges/29-smart-rockets-in-p5js/", "note": "動手做一個會演化的火箭，實際體會族群怎麼一代代變好。"},
    {"type": "論文", "lang": "en", "title": "Flocks, herds and schools: A distributed behavioral model", "by": "Craig W. Reynolds", "year": "1987", "url": "https://doi.org/10.1145/37401.37406", "note": "群集行為最早的正式論文，成群物種設計的理論起點。"},
    {"type": "論文", "lang": "en", "title": "Evolving virtual creatures", "by": "Karl Sims", "year": "1994", "url": "https://doi.org/10.1145/192161.192167", "note": "身體形狀跟行為一起演化的經典研究，很適合當靈感來源。"},
    {"type": "教學", "lang": "en", "title": "Predator-Prey Dynamics: Lotka-Volterra", "by": "M. Beals, L. Gross, S. Harrell（NIMBioS／University of Tennessee）", "year": "1999", "url": "https://legacy.nimbios.org/~gross/bioed/bealsmodules/predator-prey.html", "note": "掠食者跟獵物數量會互相影響，物種之間關係可以怎麼設計。"},
    {"type": "案例", "lang": "en", "title": "Tierra home page", "by": "Thomas S. Ray", "year": "", "url": "https://tomray.me/tierra/", "note": "讓程式互相競爭資源並演化，族群概念的另一種實作案例。"},
  ],
  "M5": [
    {"type": "官方文件", "lang": "en", "title": "p5.js noise() 函式參考", "by": "p5.js", "year": "", "url": "https://p5js.org/reference/p5/noise/", "note": "地形紋理與生物擺動要用它，數值連續不會忽然跳動。"},
    {"type": "教學", "lang": "en", "title": "Perlin Noise Flow Field 教學", "by": "The Coding Train", "year": "2016", "url": "https://thecodingtrain.com/challenges/24-perlin-noise-flow-field/", "note": "示範怎麼用 noise 做出會流動的向量場，適合做棲地氣流水流。"},
    {"type": "論文", "lang": "en", "title": "Modeling Trees with a Space Colonization Algorithm", "by": "Runions, Lane, Prusinkiewicz", "year": "2007", "url": "https://doi.org/10.2312/NPH/NPH07/063-070", "note": "樹狀結構長成演算法，想做棲地植被或血管狀生物可以參考。"},
    {"type": "官方文件", "lang": "en", "title": "WaveFunctionCollapse 演算法官方實作", "by": "mxgmn (Maxim Gumin)", "year": "", "url": "https://github.com/mxgmn/WaveFunctionCollapse", "note": "從一張範例圖自動生成相似地圖，適合做會變化的棲地地形。"},
    {"type": "官方文件", "lang": "en", "title": "ml5.js HandPose 官方文件", "by": "ml5.js", "year": "", "url": "https://docs.ml5js.org/#/reference/handpose", "note": "偵測手部21個關鍵點，做手部互動生物的技術依據。"},
    {"type": "官方文件", "lang": "en", "title": "ml5.js FaceMesh 官方文件", "by": "ml5.js", "year": "", "url": "https://docs.ml5js.org/#/reference/facemesh", "note": "偵測臉部468個特徵點，做臉部互動生物的技術依據。"},
  ],
  "M6": [
    {"type": "官方文件", "lang": "en", "title": "GitHub Pages 快速入門", "by": "GitHub", "year": "", "url": "https://docs.github.com/en/pages/quickstart", "note": "期末上線的官方步驟，照著做就能把作品發布成網頁。"},
    {"type": "官方文件", "lang": "en", "title": "GitHub Pages 建立網站官方教學", "by": "GitHub", "year": "", "url": "https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site", "note": "比快速入門更細，發布設定卡關時回來查。"},
    {"type": "科普文章", "lang": "en", "title": "V&A 展覽文字撰寫指南", "by": "Victoria and Albert Museum", "year": "2018", "url": "https://www.vam.ac.uk/blog/museum-life/getting-it-write", "note": "寫作品說明牌時參考，教你把複雜想法寫得讓觀眾看得懂。"},
    {"type": "官方文件", "lang": "en", "title": "詮釋文字撰寫指南", "by": "Museums Galleries Scotland", "year": "", "url": "https://www.museumsgalleriesscotland.org.uk/advice-article/creating-interpretive-text/", "note": "另一份寫導覽文字的實用建議，重點是文字要精簡到位。"},
    {"type": "官方文件", "lang": "en", "title": "Time Based Media 維護說明", "by": "Tate", "year": "", "url": "https://www.tate.org.uk/about-us/conservation/time-based-media", "note": "美術館怎麼長期維護會壞掉的科技藝術作品，展演前必看。"},
    {"type": "官方文件", "lang": "en", "title": "Inside Installations 研究計畫", "by": "Tate", "year": "", "url": "https://www.tate.org.uk/about-us/projects/inside-installations", "note": "裝置藝術現場怎麼顧，觀眾互動出狀況時可以參考的做法。"},
  ],
  "algorithms": [
    {"type": "教學", "lang": "en", "title": "Reaction-Diffusion Tutorial", "by": "Karl Sims", "year": "", "url": "https://karlsims.com/rd.html", "note": "兩種化學物質互相作用就長出花紋，能拿來設計生物皮膚紋理。"},
    {"type": "官方文件", "lang": "en", "title": "Conway's Game of Life", "by": "LifeWiki", "year": "", "url": "https://conwaylife.com/wiki/Conway%27s_Game_of_Life", "note": "生命遊戲規則說明，簡單規則長出複雜圖案的經典案例。"},
    {"type": "科普文章", "lang": "en", "title": "Lenia", "by": "Bert Wang-Chak Chan", "year": "", "url": "https://chakazul.github.io/lenia.html", "note": "生命遊戲的連續版本，長出來的形態更像真的生物。"},
    {"type": "書", "lang": "en", "title": "The Nature of Code — Chapter 7: Cellular Automata", "by": "Daniel Shiffman", "year": "", "url": "https://natureofcode.com/cellular-automata/", "note": "從最簡單的一維規則講到生命遊戲，適合搭配上一項一起看。"},
    {"type": "官方文件", "lang": "en", "title": "noise()", "by": "p5.js Foundation（Perlin noise 原作者 Ken Perlin）", "year": "", "url": "https://p5js.org/reference/p5/noise/", "note": "Perlin noise 官方說明，讓移動或形狀看起來自然不死板。"},
    {"type": "科普文章", "lang": "en", "title": "iquilezles.org — articles", "by": "Inigo Quilez", "year": "", "url": "https://iquilezles.org/articles/", "note": "圖形技法文章庫，想做更細緻的造型效果時進階再查。"},
    {"type": "科普文章", "lang": "en", "title": "Boids (Flocks, Herds, and Schools: a Distributed Behavioral Model)", "by": "Craig Reynolds", "year": "", "url": "https://www.red3d.com/cwr/boids/", "note": "群集演算法的最初說明，鳥群魚群怎麼靠簡單規則聚在一起。"},
  ],
  "sensing": [
    {"type": "官方文件", "lang": "en", "title": "ml5.js 官方網站", "by": "ml5.js", "year": "", "url": "https://ml5js.org/", "note": "感測互動的起點，先看有哪些現成模型可以直接用。"},
    {"type": "教學", "lang": "en", "title": "ml5.js HandPose 線上範例（p5.js Web Editor）", "by": "ml5.js", "year": "", "url": "https://editor.p5js.org/ml5/sketches/QGH3dwJ1A", "note": "可直接開啟修改的完整範例，照著改比從零寫容易上手。"},
    {"type": "官方文件", "lang": "en", "title": "MediaPipe Hand Landmarker 官方文件", "by": "Google", "year": "", "url": "https://developers.google.com/edge/mediapipe/solutions/vision/hand_landmarker", "note": "ml5.js 底層用的手部偵測模型，想知道原理可以查這裡。"},
    {"type": "官方文件", "lang": "en", "title": "MediaPipe Face Landmarker 官方文件", "by": "Google", "year": "", "url": "https://developers.google.com/edge/mediapipe/solutions/vision/face_landmarker", "note": "臉部偵測的底層模型文件，faceMesh 出問題時回這裡查。"},
    {"type": "官方文件", "lang": "en", "title": "Teachable Machine", "by": "Google", "year": "", "url": "https://teachablemachine.withgoogle.com/", "note": "不用寫程式也能訓練自己的分類模型，適合快速做原型。"},
    {"type": "影片", "lang": "en", "title": "Hand Pose Detection with ml5.js（教學影片）", "by": "The Coding Train", "year": "2024", "url": "https://www.youtube.com/watch?v=vfNHdVbE-l4", "note": "跟著做一次手部繪畫互動，比看文件更快抓到用法。"},
    {"type": "論文", "lang": "en", "title": "人臉辨識技術的隱私與倫理探討", "by": "Frontiers in Big Data", "year": "2024", "url": "https://www.frontiersin.org/journals/big-data/articles/10.3389/fdata.2024.1337465/full", "note": "用鏡頭做互動作品前，先想清楚拍到觀眾臉部的界線在哪。"},
  ],
  "cases": [
    {"type": "案例", "lang": "en", "title": "A-Volve", "by": "Christa Sommerer, Laurent Mignonneau", "year": "1994", "url": "https://www.ntticc.or.jp/en/archive/works/a-volve/", "note": "經典互動生物作品，觀眾的動作真的會影響虛擬生物的行為。"},
    {"type": "案例", "lang": "en", "title": "Electric Sheep", "by": "Scott Draves", "year": "", "url": "https://electricsheep.org/", "note": "全球電腦一起養的演化動畫羊群，群眾協作生成生命的例子。"},
    {"type": "案例", "lang": "en", "title": "Evolved Virtual Creatures", "by": "Karl Sims", "year": "1994", "url": "https://www.karlsims.com/evolved-virtual-creatures.html", "note": "經典研究，看生物怎麼靠演算法自己長出行走的方法。"},
    {"type": "案例", "lang": "en", "title": "Strandbeest", "by": "Theo Jansen", "year": "", "url": "https://www.strandbeest.com/", "note": "風力驅動的沙灘動物，機械結構模擬生命行為的代表作。"},
    {"type": "案例", "lang": "en", "title": "Sofia Crespo 官方網站", "by": "Sofia Crespo", "year": "", "url": "https://sofiacrespo.com/", "note": "當代用 AI 生成人工生命形態的藝術家，可看最新做法。"},
    {"type": "案例", "lang": "en", "title": "林珮淳《夏娃克隆》系列", "by": "林珮淳", "year": "", "url": "https://linpeychwen.com/cv/", "note": "台灣新媒體藝術家，《夏娃克隆》系列以數位複製的人造女性回應科技造物，2023 年由國美館典藏。"},
  ],
  "ai-policy": [
    {"type": "官方文件", "lang": "zh", "title": "生成式AI工具之教學因應措施", "by": "國立臺灣大學教學發展中心", "year": "", "url": "https://www.dlc.ntu.edu.tw/ai-tools/", "note": "台大公告的AI使用原則，交報告要標註使用情形。"},
    {"type": "官方文件", "lang": "zh", "title": "人工智慧應用教學指引", "by": "國立臺灣師範大學教學發展中心", "year": "2026", "url": "https://ctld.ntnu.edu.tw/generative_ai", "note": "師大版本另外列出學生該遵守的規範，可互相對照。"},
    {"type": "官方文件", "lang": "zh", "title": "大學校園因應生成式AI之指引及教學建議", "by": "教育部臺灣學術倫理教育資源中心", "year": "2023", "url": "https://ethics.moe.edu.tw/resource/epaper/html/21/", "note": "說明AI生成內容要自己查證，寫作中也要適度揭露。"},
    {"type": "官方文件", "lang": "zh", "title": "臺灣對於生成式AI的規範", "by": "臺灣學術倫理教育資源中心", "year": "", "url": "https://ethics-s.moe.edu.tw/static/ethics/u03/p14.html", "note": "整理台灣政府與學術單位對生成式 AI 的規範，包括 2026 年頒布的人工智慧基本法。"},
    {"type": "官方文件", "lang": "zh", "title": "行政院及所屬機關（構）使用生成式AI參考指引", "by": "國家科學及技術委員會", "year": "2023", "url": "https://www.nstc.gov.tw/folksonomy/list/c79bf57b-dc94-4aff-8d14-3262b5559cfc?l=ch", "note": "政府機關使用AI要揭露的官方版本，寫作揭露可參照。"},
    {"type": "教學", "lang": "en", "title": "How to Cite AI Generated Content（APA格式）", "by": "Purdue University Libraries", "year": "", "url": "https://guides.lib.purdue.edu/c.php?g=1371380&p=10135074", "note": "美國大學圖書館整理的APA引用AI格式，附完整範例。"},
  ],
  "setup": [
    {"type": "官方文件", "lang": "en", "title": "Using AGY CLI", "by": "Google Antigravity Docs", "year": "", "url": "https://antigravity.google/docs/cli/using/", "note": "agy指令怎麼打的官方手冊，設定與快速鍵都在這。"},
    {"type": "教學", "lang": "en", "title": "Hands-on with Antigravity CLI", "by": "Google Codelabs", "year": "", "url": "https://codelabs.developers.google.com/antigravity-cli-hands-on", "note": "官方逐步教學，從安裝到打出第一個指令都照著做。"},
    {"type": "官方文件", "lang": "en", "title": "GitHub Student Developer Pack", "by": "GitHub Education", "year": "", "url": "https://education.github.com/pack", "note": "用學校信箱申請，Codespaces等工具靠學生資格拿。"},
    {"type": "官方文件", "lang": "en", "title": "What are GitHub Codespaces?", "by": "GitHub Docs", "year": "", "url": "https://docs.github.com/en/codespaces/overview", "note": "雲端開發環境官方說明，電腦跑不動時的備案。"},
    {"type": "官方文件", "lang": "zh", "title": "Windows 終端機概觀", "by": "Microsoft Learn", "year": "", "url": "https://learn.microsoft.com/zh-tw/windows/terminal/", "note": "Windows要用終端機先裝這個，官方繁中說明。"},
    {"type": "官方文件", "lang": "zh", "title": "Mac 終端機使用手冊", "by": "Apple 支援", "year": "", "url": "https://support.apple.com/zh-tw/guide/terminal/welcome/mac", "note": "整本Mac終端機手冊，設定與操作方式查這裡就夠。"},
    {"type": "教學", "lang": "zh", "title": "開始使用 PowerShell - PowerShell 101", "by": "Microsoft Learn", "year": "", "url": "https://learn.microsoft.com/zh-tw/powershell/scripting/learn/ps101/01-getting-started?view=powershell-7.6", "note": "Windows同學開工前的實際操作步驟，跟著做一次。"},
  ],
  "submission": [
    {"type": "官方文件", "lang": "en", "title": "建立新的 repository", "by": "GitHub", "year": "", "url": "https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-new-repository", "note": "交作業的第一步，先開一個屬於自己的程式碼庫。"},
    {"type": "官方文件", "lang": "en", "title": "從範本建立 repository", "by": "GitHub", "year": "", "url": "https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template", "note": "老師如果有給模板，從這裡一鍵複製出自己的專案。"},
    {"type": "官方文件", "lang": "en", "title": "上傳檔案到 repository", "by": "GitHub", "year": "", "url": "https://docs.github.com/en/repositories/working-with-files/managing-files/adding-a-file-to-a-repository", "note": "把 sketch.js 等檔案放上去的官方步驟，網頁介面就能做。"},
    {"type": "官方文件", "lang": "en", "title": "認識 Git（commit 與 push 概念）", "by": "GitHub", "year": "", "url": "https://docs.github.com/en/get-started/using-git/about-git", "note": "commit 跟 push 到底在做什麼，這頁把基本觀念講清楚。"},
    {"type": "書", "lang": "zh", "title": "Pro Git 繁體中文版", "by": "Scott Chacon、Ben Straub", "year": "2014", "url": "https://git-scm.com/book/zh-tw/v2", "note": "免費電子書，Git 觀念想查更深可以整本翻。"},
    {"type": "官方文件", "lang": "en", "title": "GitHub Desktop 官方文件", "by": "GitHub", "year": "", "url": "https://docs.github.com/en/desktop", "note": "不想打指令的話，這個圖形介面工具可以代替終端機。"},
  ],
}
