// 延伸閱讀（單一來源）：key＝App 的 section id 或里程碑 id（M0–M6）
// 每一筆都在 2026-09-17 實際打開核對過標題與內容，論文 DOI 經 Crossref 核對；改連結後請重新檢查

export const READING_NOTE = '連結都在 2026-09-17 實際打開核對過，網站改版可能讓連結失效，發現打不開請告訴老師。'

export const READINGS = {
  "project": [
    {"type": "書", "lang": "en", "title": "After Man: A Zoology of the Future", "by": "Dougal Dixon", "year": "1981", "url": "https://www.dougal-dixon.co.uk/after-man", "note": "推測演化經典，想像人類滅絕後動物如何演化成新物種。"},
    {"type": "書", "lang": "en", "title": "On the Origin of Species（1859 初版全文）", "by": "Charles Darwin", "year": "1859", "url": "https://darwin-online.org.uk/content/frameset?itemID=F373&viewtype=text&pageseq=1", "note": "天擇論的原典全文，想像人類消失後生物怎麼重新演化，可以從這裡讀起。"},
    {"type": "官方文件", "lang": "en", "title": "The Future Is Wild（官方網站）", "by": "The Future Is Wild 製作團隊", "year": "", "url": "https://www.thefutureiswild.com/", "note": "製作方官網，三集分別推演 500 萬年、1 億年、2 億年後的地球與生物。"},
    {"type": "書", "lang": "en", "title": "All Tomorrows: A Billion Year Chronicle of the Myriad Species and Mixed Fortunes of Man", "by": "C. M. Kösemen", "year": "2006", "url": "http://cmkosemen.com/books.html", "note": "作者本人的書目頁，2006 年的推測演化作品，想像人類在十億年間變成各種物種。"},
  ],
  "creature": [
    {"type": "影片", "lang": "en", "title": "How trees talk to each other", "by": "Suzanne Simard", "year": "2016", "url": "https://www.ted.com/talks/suzanne_simard_how_trees_talk_to_each_other", "note": "菌根網路讓森林裡的樹互相傳訊號與養分，共生也是一種溝通。"},
    {"type": "影片", "lang": "en", "title": "How bacteria \"talk\"", "by": "Bonnie Bassler", "year": "2009", "url": "https://www.ted.com/talks/bonnie_bassler_how_bacteria_talk", "note": "細菌靠化學訊號集體決策的群體感應，是最小尺度的生物溝通。"},
    {"type": "書", "lang": "en", "title": "The Descent of Man, and Selection in Relation to Sex（1871 初版）", "by": "Charles Darwin", "year": "1871", "url": "https://darwin-online.org.uk/converted/published/1871_Descent_F937/1871_Descent_F937.1.html", "note": "性擇論的原始出處，設計生物外觀與求偶行為時可以直接參考。"},
    {"type": "論文", "lang": "en", "title": "Thermus aquaticus gen. n. and sp. n., a Nonsporulating Extreme Thermophile", "by": "Thomas D. Brock, Hudson Freeze", "year": "1969", "url": "https://doi.org/10.1128/jb.98.1.289-297.1969", "note": "黃石公園溫泉發現極端嗜熱菌的原始論文，是極端環境生物範例。"},
    {"type": "官方文件", "lang": "zh", "title": "雜頭翁的繁殖能力（烏頭翁與白頭翁雜交說明）", "by": "農業部生物多樣性研究所（原特有生物研究保育中心）", "year": "不詳", "url": "https://www.tbri.gov.tw/view.php?id=239&subtheme=&theme=qa", "note": "官方說明烏頭翁與白頭翁在野外雜交、後代還能繁殖的原因，是台灣本土的混種例子。"},
    {"type": "論文", "lang": "en", "title": "Submarine Thermal Springs on the Galápagos Rift", "by": "John B. Corliss et al.", "year": "1979", "url": "https://doi.org/10.1126/science.203.4385.1073", "note": "深海熱泉化學合成生態系的原始發現，是不靠陽光生物的範例。"},
  ],
  "method": [
    {"type": "教學", "lang": "en", "title": "SIFT (The Four Moves)", "by": "Mike Caulfield", "year": "2019", "url": "https://hapgood.us/2019/06/19/sift-the-four-moves/", "note": "查證資訊來源的四步驟方法，AI給的內容也要照樣核對。"},
    {"type": "教學", "lang": "en", "title": "Civic Online Reasoning（橫向閱讀教材）", "by": "Digital Inquiry Group（原史丹佛歷史教育小組）", "year": "", "url": "https://cor.inquirygroup.org/", "note": "史丹佛教的橫向閱讀，離開頁面查別處說法再判斷。"},
    {"type": "教學", "lang": "zh", "title": "必修：辨識假訊息的識讀心法", "by": "台灣事實查核中心", "year": "2025", "url": "https://school.tfc-taiwan.org.tw/learning-resources/media-literacy/", "note": "台灣事實查核中心教SIFT與疑想查問戳，好懂又在地。"},
    {"type": "論文", "lang": "en", "title": "Lateral reading: College students learn to critically evaluate internet sources in an online course", "by": "Joel Breakstone, Mark Smith, Priscilla Connors, Teresa Ortega, Darby Kerr, Sam Wineburg", "year": "2021", "url": "https://doi.org/10.37016/mr-2020-56", "note": "美國實驗證實橫向閱讀教了就會用，查證力明顯進步。"},
    {"type": "官方文件", "lang": "zh", "title": "開源衡量準則", "by": "GitHub Open Source Guides", "year": "", "url": "https://opensource.guide/zh-hant/metrics/", "note": "官方教材列出評估開源專案的具體指標，別只看星星。"},
  ],
  "M0": [
    {"type": "影片", "lang": "en", "title": "Transformers, the tech behind LLMs | Deep Learning Chapter 5（原名 But what is a GPT?）", "by": "3Blue1Brown (Grant Sanderson)", "year": "2024", "url": "https://www.youtube.com/watch?v=wjZofJX0v4M", "note": "動畫解釋Transformer怎麼運作，有中文字幕可開。"},
    {"type": "官方文件", "lang": "zh", "title": "什麼是 Mac 的「終端機」？", "by": "Apple 支援", "year": "", "url": "https://support.apple.com/zh-tw/guide/terminal/trmld4c92d55/mac", "note": "先搞懂終端機是什麼再開始，蘋果官方繁中說明。"},
    {"type": "官方文件", "lang": "zh", "title": "什麼是 PowerShell？", "by": "Microsoft Learn", "year": "", "url": "https://learn.microsoft.com/zh-tw/powershell/scripting/overview?view=powershell-7.6", "note": "Windows同學對照看，觀念和Mac終端機互通。"},
    {"type": "論文", "lang": "en", "title": "Why Language Models Hallucinate", "by": "Adam Tauman Kalai, Ofir Nachum, Santosh S. Vempala, Edwin Zhang", "year": "2025", "url": "https://arxiv.org/abs/2509.04664", "note": "OpenAI原始論文解釋AI為什麼會一本正經講錯話的原因。"},
  ],
  "M1": [
    {"type": "論文", "lang": "en", "title": "Long-term census data reveal abundant wildlife populations at Chernobyl", "by": "T.G. Deryabina et al.", "year": "2015", "url": "https://doi.org/10.1016/j.cub.2015.08.017", "note": "車諾比禁區真實普查資料，是課堂想像世界前該看的第一手證據。"},
    {"type": "官方文件", "lang": "en", "title": "Chernobyl, Ukraine", "by": "NASA Earth Observatory", "year": "", "url": "https://science.nasa.gov/earth/earth-observatory/chernobyl-ukraine-39679", "note": "NASA衛星影像對照人類撤離前後的植被變化，證據具體好懂。"},
    {"type": "官方文件", "lang": "zh", "title": "論壇：眼見不為憑——查證作為媒體素養的第一步", "by": "台灣科技媒體中心（SMC）", "year": "", "url": "https://smctw.tw/8769", "note": "教怎麼查證科學說法真假，做世界研究前先練這個習慣。"},
    {"type": "書", "lang": "en", "title": "The World Without Us", "by": "Alan Weisman", "year": "2007", "url": "http://worldwithoutus.com/index2.html", "note": "作者官方網站，講人類消失後建築與自然如何逐漸崩解回歸。"},
    {"type": "論文", "lang": "en", "title": "Where the wild things are: influence of radiation on the distribution of four mammalian species within the Chernobyl Exclusion Zone", "by": "Sarah C. Webster et al.", "year": "2016", "url": "https://doi.org/10.1002/fee.1227", "note": "車諾比禁區哺乳類分布調查，看人類離開後野生動物如何回來。"},
    {"type": "論文", "lang": "en", "title": "Strong effects of ionizing radiation from Chernobyl on mutation rates", "by": "Anders Pape Møller, Timothy A. Mousseau", "year": "2015", "url": "https://doi.org/10.1038/srep08363", "note": "車諾比輻射對突變率的研究，可以對照野生動物分布的另一面說法。"},
  ],
  "M2": [
    {"type": "官方文件", "lang": "en", "title": "p5.js Tutorials", "by": "p5.js Foundation", "year": "", "url": "https://p5js.org/tutorials/", "note": "官方教學總覽，找繪圖與互動基礎的入門單元練習。"},
    {"type": "官方文件", "lang": "en", "title": "p5.js Reference", "by": "p5.js Foundation", "year": "", "url": "https://p5js.org/reference/", "note": "查每個函式怎麼用，寫程式卡住時第一個查的地方。"},
    {"type": "官方文件", "lang": "en", "title": "p5.js Web Editor", "by": "p5.js Foundation", "year": "", "url": "https://editor.p5js.org/", "note": "免安裝直接寫程式碼跑畫面，上課與交作業都用它。"},
    {"type": "教學", "lang": "en", "title": "Code! Programming with p5.js", "by": "Daniel Shiffman / The Coding Train", "year": "", "url": "https://thecodingtrain.com/tracks/code-programming-with-p5-js", "note": "跟著影片從形狀、變數練到迴圈，零基礎入門的完整路線。"},
  ],
  "M3": [
    {"type": "書", "lang": "en", "title": "The Nature of Code — Chapter 5: Autonomous Agents", "by": "Daniel Shiffman", "year": "", "url": "https://natureofcode.com/autonomous-agents/", "note": "講清楚轉向力怎麼讓一個點看起來像有意志地移動。"},
    {"type": "書", "lang": "en", "title": "The Nature of Code — Chapter 2: Forces", "by": "Daniel Shiffman", "year": "", "url": "https://natureofcode.com/forces/", "note": "先懂力怎麼加在物體上，是後面行為模擬的基礎觀念。"},
    {"type": "書", "lang": "en", "title": "The Nature of Code — Appendix: Creature Design", "by": "Daniel Shiffman / Zannah Marsh", "year": "", "url": "https://natureofcode.com/appendix-creature/", "note": "教怎麼用簡單形狀畫出生物，外形能暗示牠的個性與行為。"},
    {"type": "科普文章", "lang": "en", "title": "Steering Behaviors For Autonomous Characters", "by": "Craig Reynolds", "year": "", "url": "https://www.red3d.com/cwr/steer/", "note": "轉向行為的原始整理，尋找、追逐、閃避都從這裡來。"},
    {"type": "書", "lang": "en", "title": "Vehicles: Experiments in Synthetic Psychology", "by": "Valentino Braitenberg", "year": "1984", "url": "https://mitpress.mit.edu/9780262521123/vehicles/", "note": "簡單線路接法就長出像有情緒的行為，設計物種很好的靈感。"},
    {"type": "影片", "lang": "en", "title": "5.1 Steering Agents", "by": "Daniel Shiffman / The Coding Train", "year": "", "url": "https://thecodingtrain.com/tracks/the-nature-of-code-2/noc/5-autonomous-agents/1-steering-agents", "note": "影片版自主代理入門，先懂觀念再自己動手寫程式碼。"},
  ],
  "M4": [
    {"type": "書", "lang": "en", "title": "The Nature of Code — Chapter 9: Evolutionary Computing", "by": "Daniel Shiffman", "year": "", "url": "https://natureofcode.com/genetic-algorithms/", "note": "講清楚演化運算的流程，適應、選擇、變異怎麼寫成程式。"},
    {"type": "教學", "lang": "en", "title": "#29 — Smart Rockets in p5.js", "by": "Daniel Shiffman / The Coding Train", "year": "", "url": "https://thecodingtrain.com/challenges/29-smart-rockets-in-p5js/", "note": "動手做一個會演化的火箭，實際體會族群怎麼一代代變好。"},
    {"type": "論文", "lang": "en", "title": "Flocks, herds and schools: A distributed behavioral model", "by": "Craig W. Reynolds", "year": "1987", "url": "https://doi.org/10.1145/37401.37406", "note": "群集行為最早的正式論文，成群物種設計的理論起點。"},
    {"type": "論文", "lang": "en", "title": "Evolving virtual creatures", "by": "Karl Sims", "year": "1994", "url": "https://doi.org/10.1145/192161.192167", "note": "身體形狀跟行為一起演化的經典研究，很適合當靈感來源。"},
    {"type": "案例", "lang": "en", "title": "Tierra home page", "by": "Thomas S. Ray", "year": "", "url": "https://tomray.me/tierra/", "note": "讓程式互相競爭資源並演化，族群概念的另一種實作案例。"},
    {"type": "論文", "lang": "en", "title": "Fluctuations in the Abundance of a Species considered Mathematically", "by": "Vito Volterra", "year": "1926", "url": "https://doi.org/10.1038/118558a0", "note": "Volterra描述物種數量消長的原始數學模型，用來理解生態互動。"},
  ],
  "M5": [
    {"type": "官方文件", "lang": "en", "title": "p5.js noise() 函式參考", "by": "p5.js", "year": "", "url": "https://p5js.org/reference/p5/noise/", "note": "地形紋理與生物擺動要用它，數值連續不會忽然跳動。"},
    {"type": "教學", "lang": "en", "title": "Perlin Noise Flow Field 教學", "by": "The Coding Train", "year": "2016", "url": "https://thecodingtrain.com/challenges/24-perlin-noise-flow-field/", "note": "示範怎麼用 noise 做出會流動的向量場，適合做棲地氣流水流。"},
    {"type": "論文", "lang": "en", "title": "Modeling Trees with a Space Colonization Algorithm", "by": "Runions, Lane, Prusinkiewicz", "year": "2007", "url": "https://doi.org/10.2312/NPH/NPH07/063-070", "note": "樹狀結構長成演算法，想做棲地植被或血管狀生物可以參考。"},
    {"type": "官方文件", "lang": "en", "title": "WaveFunctionCollapse 演算法官方實作", "by": "mxgmn (Maxim Gumin)", "year": "", "url": "https://github.com/mxgmn/WaveFunctionCollapse", "note": "從一張範例圖自動生成相似地圖，適合做會變化的棲地地形。"},
    {"type": "官方文件", "lang": "en", "title": "ml5.js HandPose 官方文件", "by": "ml5.js", "year": "", "url": "https://docs.ml5js.org/#/reference/handpose", "note": "偵測手部21個關鍵點，做手部互動生物的技術依據。"},
    {"type": "官方文件", "lang": "en", "title": "ml5.js FaceMesh 官方文件", "by": "ml5.js", "year": "", "url": "https://docs.ml5js.org/#/reference/facemesh", "note": "偵測臉部468個特徵點，做臉部互動生物的技術依據。"},
  ],
  "M6": [
    {"type": "官方文件", "lang": "en", "title": "GitHub Pages 快速入門", "by": "GitHub", "year": "", "url": "https://docs.github.com/en/pages/quickstart", "note": "期末上線的官方步驟，照著做就能把作品發布成網頁。"},
    {"type": "官方文件", "lang": "en", "title": "GitHub Pages 建立網站官方教學", "by": "GitHub", "year": "", "url": "https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site", "note": "比快速入門更細，發布設定卡關時回來查。"},
    {"type": "科普文章", "lang": "en", "title": "V&A 展覽文字撰寫指南", "by": "Victoria and Albert Museum", "year": "2018", "url": "https://www.vam.ac.uk/blog/museum-life/getting-it-write", "note": "寫作品說明牌時參考，教你把複雜想法寫得讓觀眾看得懂。"},
    {"type": "官方文件", "lang": "en", "title": "詮釋文字撰寫指南", "by": "Museums Galleries Scotland", "year": "", "url": "https://www.museumsgalleriesscotland.org.uk/advice-article/creating-interpretive-text/", "note": "另一份寫導覽文字的實用建議，重點是文字要精簡到位。"},
    {"type": "官方文件", "lang": "en", "title": "Time Based Media 維護說明", "by": "Tate", "year": "", "url": "https://www.tate.org.uk/about-us/conservation/time-based-media", "note": "美術館怎麼長期維護會壞掉的科技藝術作品，展演前必看。"},
    {"type": "官方文件", "lang": "en", "title": "Inside Installations 研究計畫", "by": "Tate", "year": "", "url": "https://www.tate.org.uk/about-us/projects/inside-installations", "note": "裝置藝術現場怎麼顧，觀眾互動出狀況時可以參考的做法。"},
  ],
  "algorithms": [
    {"type": "教學", "lang": "en", "title": "Reaction-Diffusion Tutorial", "by": "Karl Sims", "year": "", "url": "https://karlsims.com/rd.html", "note": "兩種化學物質互相作用就長出花紋，能拿來設計生物皮膚紋理。"},
    {"type": "科普文章", "lang": "en", "title": "Lenia", "by": "Bert Wang-Chak Chan", "year": "", "url": "https://chakazul.github.io/lenia.html", "note": "生命遊戲的連續版本，長出來的形態更像真的生物。"},
    {"type": "書", "lang": "en", "title": "The Nature of Code — Chapter 7: Cellular Automata", "by": "Daniel Shiffman", "year": "", "url": "https://natureofcode.com/cellular-automata/", "note": "從最簡單的一維規則講到生命遊戲，適合搭配上一項一起看。"},
    {"type": "官方文件", "lang": "en", "title": "noise()", "by": "p5.js Foundation（Perlin noise 原作者 Ken Perlin）", "year": "", "url": "https://p5js.org/reference/p5/noise/", "note": "Perlin noise 官方說明，讓移動或形狀看起來自然不死板。"},
    {"type": "科普文章", "lang": "en", "title": "iquilezles.org — articles", "by": "Inigo Quilez", "year": "", "url": "https://iquilezles.org/articles/", "note": "圖形技法文章庫，想做更細緻的造型效果時進階再查。"},
    {"type": "科普文章", "lang": "en", "title": "Boids (Flocks, Herds, and Schools: a Distributed Behavioral Model)", "by": "Craig Reynolds", "year": "", "url": "https://www.red3d.com/cwr/boids/", "note": "群集演算法的最初說明，鳥群魚群怎麼靠簡單規則聚在一起。"},
    {"type": "論文", "lang": "en", "title": "Mathematical Games: The fantastic combinations of John Conway's new solitaire game \"life\"", "by": "Martin Gardner", "year": "1970", "url": "https://doi.org/10.1038/scientificamerican1070-120", "note": "介紹Conway生命遊戲的原始文章，簡單規則長出複雜生命型態。"},
  ],
  "sensing": [
    {"type": "官方文件", "lang": "en", "title": "ml5.js 官方網站", "by": "ml5.js", "year": "", "url": "https://ml5js.org/", "note": "感測互動的起點，先看有哪些現成模型可以直接用。"},
    {"type": "教學", "lang": "en", "title": "ml5.js HandPose 線上範例（p5.js Web Editor）", "by": "ml5.js", "year": "", "url": "https://editor.p5js.org/ml5/sketches/QGH3dwJ1A", "note": "可直接開啟修改的完整範例，照著改比從零寫容易上手。"},
    {"type": "官方文件", "lang": "en", "title": "MediaPipe Hand Landmarker 官方文件", "by": "Google", "year": "", "url": "https://developers.google.com/edge/mediapipe/solutions/vision/hand_landmarker", "note": "ml5.js 底層用的手部偵測模型，想知道原理可以查這裡。"},
    {"type": "官方文件", "lang": "en", "title": "MediaPipe Face Landmarker 官方文件", "by": "Google", "year": "", "url": "https://developers.google.com/edge/mediapipe/solutions/vision/face_landmarker", "note": "臉部偵測的底層模型文件，faceMesh 出問題時回這裡查。"},
    {"type": "官方文件", "lang": "en", "title": "Teachable Machine", "by": "Google", "year": "", "url": "https://teachablemachine.withgoogle.com/", "note": "不用寫程式也能訓練自己的分類模型，適合快速做原型。"},
    {"type": "影片", "lang": "en", "title": "Hand Pose Detection with ml5.js（教學影片）", "by": "The Coding Train", "year": "2024", "url": "https://www.youtube.com/watch?v=vfNHdVbE-l4", "note": "跟著做一次手部繪畫互動，比看文件更快抓到用法。"},
    {"type": "法規", "lang": "zh", "title": "個人資料保護法 第 2 條", "by": "全國法規資料庫（法務部）", "year": "", "url": "https://law.moj.gov.tw/LawClass/LawSingle.aspx?pcode=I0050021&flno=2", "note": "條文把「特徵」和可以直接或間接認出一個人的資料都算個人資料，用鏡頭做互動前先讀。"},
  ],
  "cases": [
    {"type": "案例", "lang": "en", "title": "A-Volve", "by": "Christa Sommerer, Laurent Mignonneau", "year": "1994", "url": "https://www.ntticc.or.jp/en/archive/works/a-volve/", "note": "經典互動生物作品，觀眾的動作真的會影響虛擬生物的行為。"},
    {"type": "案例", "lang": "en", "title": "Electric Sheep", "by": "Scott Draves", "year": "", "url": "https://electricsheep.org/", "note": "全球電腦一起養的演化動畫羊群，群眾協作生成生命的例子。"},
    {"type": "案例", "lang": "en", "title": "Evolved Virtual Creatures", "by": "Karl Sims", "year": "1994", "url": "https://www.karlsims.com/evolved-virtual-creatures.html", "note": "經典研究，看生物怎麼靠演算法自己長出行走的方法。"},
    {"type": "案例", "lang": "en", "title": "Strandbeest", "by": "Theo Jansen", "year": "", "url": "https://www.strandbeest.com/", "note": "風力驅動的沙灘動物，機械結構模擬生命行為的代表作。"},
    {"type": "案例", "lang": "en", "title": "Sofia Crespo 官方網站", "by": "Sofia Crespo", "year": "", "url": "https://sofiacrespo.com/", "note": "當代用 AI 生成人工生命形態的藝術家，可看最新做法。"},
    {"type": "案例", "lang": "en", "title": "林珮淳《夏娃克隆》系列", "by": "林珮淳", "year": "", "url": "https://linpeychwen.com/cv/", "note": "台灣新媒體藝術家，《夏娃克隆》系列以數位複製的人造女性回應科技造物，2023 年由國美館典藏。"},
  ],
  "ai-policy": [
    {"type": "官方文件", "lang": "zh", "title": "生成式AI工具之教學因應措施", "by": "國立臺灣大學教學發展中心", "year": "", "url": "https://www.dlc.ntu.edu.tw/ai-tools/", "note": "台大公告的AI使用原則，交報告要標註使用情形。"},
    {"type": "官方文件", "lang": "zh", "title": "人工智慧應用教學指引", "by": "國立臺灣師範大學教學發展中心", "year": "2026", "url": "https://ctld.ntnu.edu.tw/generative_ai", "note": "師大版本另外列出學生該遵守的規範，可互相對照。"},
    {"type": "官方文件", "lang": "zh", "title": "大學校園因應生成式AI之指引及教學建議", "by": "教育部臺灣學術倫理教育資源中心", "year": "2023", "url": "https://ethics.moe.edu.tw/resource/epaper/html/21/", "note": "說明AI生成內容要自己查證，寫作中也要適度揭露。"},
    {"type": "官方文件", "lang": "zh", "title": "臺灣對於生成式AI的規範", "by": "臺灣學術倫理教育資源中心", "year": "", "url": "https://ethics-s.moe.edu.tw/static/ethics/u03/p14.html", "note": "整理台灣政府與學術單位對生成式 AI 的規範，包括 2026 年頒布的人工智慧基本法。"},
    {"type": "官方文件", "lang": "zh", "title": "行政院及所屬機關（構）使用生成式AI參考指引", "by": "國家科學及技術委員會", "year": "2023", "url": "https://www.nstc.gov.tw/folksonomy/list/c79bf57b-dc94-4aff-8d14-3262b5559cfc?l=ch", "note": "政府機關使用AI要揭露的官方版本，寫作揭露可參照。"},
    {"type": "官方文件", "lang": "en", "title": "How to cite ChatGPT", "by": "American Psychological Association", "year": "2023", "url": "https://apastyle.apa.org/blog/how-to-cite-chatgpt", "note": "APA官方規定引用ChatGPT的格式，作業用到AI要照這個標示。"},
  ],
  "setup": [
    {"type": "官方文件", "lang": "en", "title": "Using AGY CLI", "by": "Google Antigravity Docs", "year": "", "url": "https://antigravity.google/docs/cli/using/", "note": "agy指令怎麼打的官方手冊，設定與快速鍵都在這。"},
    {"type": "教學", "lang": "en", "title": "Hands-on with Antigravity CLI", "by": "Google Codelabs", "year": "", "url": "https://codelabs.developers.google.com/antigravity-cli-hands-on", "note": "官方逐步教學，從安裝到打出第一個指令都照著做。"},
    {"type": "官方文件", "lang": "en", "title": "GitHub Student Developer Pack", "by": "GitHub Education", "year": "", "url": "https://education.github.com/pack", "note": "用學校信箱申請，Codespaces等工具靠學生資格拿。"},
    {"type": "官方文件", "lang": "en", "title": "What are GitHub Codespaces?", "by": "GitHub Docs", "year": "", "url": "https://docs.github.com/en/codespaces/overview", "note": "雲端開發環境官方說明，電腦跑不動時的備案。"},
    {"type": "官方文件", "lang": "zh", "title": "Windows 終端機概觀", "by": "Microsoft Learn", "year": "", "url": "https://learn.microsoft.com/zh-tw/windows/terminal/", "note": "Windows要用終端機先裝這個，官方繁中說明。"},
    {"type": "官方文件", "lang": "zh", "title": "Mac 終端機使用手冊", "by": "Apple 支援", "year": "", "url": "https://support.apple.com/zh-tw/guide/terminal/welcome/mac", "note": "整本Mac終端機手冊，設定與操作方式查這裡就夠。"},
    {"type": "教學", "lang": "zh", "title": "開始使用 PowerShell - PowerShell 101", "by": "Microsoft Learn", "year": "", "url": "https://learn.microsoft.com/zh-tw/powershell/scripting/learn/ps101/01-getting-started?view=powershell-7.6", "note": "Windows同學開工前的實際操作步驟，跟著做一次。"},
  ],
  "submission": [
    {"type": "官方文件", "lang": "en", "title": "建立新的 repository", "by": "GitHub", "year": "", "url": "https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-new-repository", "note": "交作業的第一步，先開一個屬於自己的程式碼庫。"},
    {"type": "官方文件", "lang": "en", "title": "從範本建立 repository", "by": "GitHub", "year": "", "url": "https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template", "note": "老師如果有給模板，從這裡一鍵複製出自己的專案。"},
    {"type": "官方文件", "lang": "en", "title": "上傳檔案到 repository", "by": "GitHub", "year": "", "url": "https://docs.github.com/en/repositories/working-with-files/managing-files/adding-a-file-to-a-repository", "note": "把 sketch.js 等檔案放上去的官方步驟，網頁介面就能做。"},
    {"type": "官方文件", "lang": "en", "title": "認識 Git（commit 與 push 概念）", "by": "GitHub", "year": "", "url": "https://docs.github.com/en/get-started/using-git/about-git", "note": "commit 跟 push 到底在做什麼，這頁把基本觀念講清楚。"},
    {"type": "書", "lang": "zh", "title": "Pro Git 繁體中文版", "by": "Scott Chacon、Ben Straub", "year": "2014", "url": "https://git-scm.com/book/zh-tw/v2", "note": "免費電子書，Git 觀念想查更深可以整本翻。"},
    {"type": "官方文件", "lang": "en", "title": "GitHub Desktop 官方文件", "by": "GitHub", "year": "", "url": "https://docs.github.com/en/desktop", "note": "不想打指令的話，這個圖形介面工具可以代替終端機。"},
  ],
}
